"""fixed users: added email & password

Revision ID: 4e4b6af75119
Revises: 42b9ed310d6a
Create Date: 2024-11-27 22:28:07.253435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from java_luchshe.project.core.config import settings

# revision identifiers, used by Alembic.
revision: str = '4e4b6af75119'
down_revision: Union[str, None] = '42b9ed310d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False), schema=settings.POSTGRES_SCHEMA)
    op.add_column('users', sa.Column('password', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False), schema=settings.POSTGRES_SCHEMA)
    op.create_unique_constraint(None, 'users', ['email'], schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema=settings.POSTGRES_SCHEMA, type_='unique')
    op.drop_column('users', 'password', schema=settings.POSTGRES_SCHEMA)
    op.drop_column('users', 'email', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###
